require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'spec/controllers/**/*'
    - 'bin/*'
    - 'app/uploaders/*'
    - 'config/environments/*'
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 135